### ISSUE TITLE
error networkx.exception.NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')

### ISSUE THREAD

**Issue by yingchuan-d** [HexHive/BOPC#11]
Thank you for answer my last question, gannimo ! 
Now I try to use the the beginning of ngx_signal_handler function as entry. 
 But when I use "../source/BOPC.py -dd --binary nginxl --source infloop.spl --abstractions save --entry 0x000000000041c750 --format gdb", the error accurs.
The error code is :

```python
[21:04:27,701] [+] Trace searching algorithm started.
[21:04:27,701] [+] Enumerating all mappings between virtual and hardware registers
[21:04:27,701] [+]      and all mappings between variables and addresses...
G is null
Traceback (most recent call last):
  File "../source/BOPC.py", line 482, in <module>
    tsearch.trace_searching(mark)
  File "/home/dyc_lab/BOPC/source/search.py", line 916, in trace_searching
    rval = mapping.enum_mappings( self.__mapping_callback )
  File "/home/dyc_lab/BOPC/source/map.py", line 468, in enum_mappings
    ret = match.enum_max_matchings(self.__intrl_callback_reg, self.__nregs)
  File "/home/dyc_lab/BOPC/source/map.py", line 342, in enum_max_matchings
    if self.__callback( M ) < 0:
  File "/home/dyc_lab/BOPC/source/map.py", line 424, in __intrl_callback_reg
    if match.enum_max_matchings(self.__intrl_callback_var, self.__nvars) < 0:
  File "/home/dyc_lab/BOPC/source/map.py", line 299, in enum_max_matchings
    M = nx.bipartite.maximum_matching(self.__G)
  File "/home/dyc_lab/.virtualenvs/angr/local/lib/python2.7/site-packages/networkx/algorithms/bipartite/matching.py", line 146, in hopcroft_karp_matching
    left, right = bipartite_sets(G, top_nodes)
  File "/home/dyc_lab/.virtualenvs/angr/local/lib/python2.7/site-packages/networkx/algorithms/bipartite/basic.py", line 204, in sets
    if not is_connected(G):
  File "<decorator-gen-108>", line 2, in is_connected
  File "/home/dyc_lab/.virtualenvs/angr/local/lib/python2.7/site-packages/networkx/utils/decorators.py", line 73, in _not_implemented_for
    return not_implement_for_func(*args, **kwargs)
  File "/home/dyc_lab/.virtualenvs/angr/local/lib/python2.7/site-packages/networkx/algorithms/components/connected.py", line 162, in is_connected
    'for the null graph.')
networkx.exception.NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')
```

  Firstly I thought it maybe that I set an error entry, but it's not. Then I think maybe the ELF(nginxl in evaluation, and it works well) wrong, so I compile the nginx-1.4.0, and find it still report this error.
  Finally I thought if there are some wrong in CFG, for when analyze it reports hundreds times:
```python
[WARNING] Symbolic Execution at block 0x471ded failed: 'There are no usable stashes!' Much sad :( Skipping current block....
```
I know maybe I need provide more infomation but I even don't know what is vital. 
Please help me!

**Comment by yingchuan-d** [comment]
I have solved this problem with the help of kaiming!
