### ISSUE TITLE
"unwarranted" exceptions occurring

### ISSUE THREAD

**Issue by mtullsen** [HexHive/BOPC#2]
setup.sh did not work out of the box, my install is such:

    pipenv install angr==7.8.9.26
    pipenv install claripy==7.8.9.26
    pipenv install networkx==1.11
       # got error here! so I did the next:
    pipenv install networkx==2.1
    pipenv install matplotlib
    pipenv install simuvex
    pipenv install graphviz==0.8.1
    pipenv install pygraphviz==1.3.1

Now, when I do

    __binary__=~/src/3rd/BOPC/evaluation/nginx1
    ./source/BOPC.py -dd -b $__binary__ -a saveonly

I get this

    [*] Starting BOPC v2.1 at 10/11/2018 23:05
    [23:05:24,881] [+] Generating CFG. It might take a while...
    WARNING | 2018-11-10 23:05:36,854 | angr.engines.successors | Exit state has over 256 possible solutions. Likely unconstrained; skipping. <BV64 global_c000000_13_64{UNINITIALIZED}>
    WARNING | 2018-11-10 23:05:36,927 | claripy.vsa.strided_interval | Reversing a real strided-interval <64>0x1[0x500000000000000, 0x5ffffffffffffff]R(uninit) is bad
    WARNING | 2018-11-10 23:05:36,970 | angr.engines.successors | Exit state has
    over 256 possible solutions. Likely unconstrained; skipping. <BV64
    Reverse(unconstrained_read_25_64)>
    ...
    WARNING | 2018-11-10 23:05:39,814 | angr.engines.successors | Exit state has over 256 possible solutions. Likely unconstrained; skipping. <BV64 global_8003f6780_312_64{UNINITIALIZED}>
    WARNING | 2018-11-10 23:05:39,854 | angr.engines.successors | Exit state has over 256 possible solutions. Likely unconstrained; skipping. <BV64 global_c0001b4_317_64{UNINITIALIZED}>
    [23:05:45,133] [+] CFG generated.
    [23:05:45,134] [+] Normalizing CFG...
    [23:05:45,885] [+] Done.
    [23:05:45,897] [*] CFG has 24169 nodes and 44565 edges
    [23:05:45,951] [+] Basic block abstraction process started.
    defaultdict(<type 'list'>, {'pruned': [], 'deadended': [], 'active': [],
    'unconstrained': [], 'errored': [], 'unsat': [], 'stashed': []})
    ...
    [23:23:02,662] [WARNING] Symbolic Execution at block 0x45d996 failed: 'There are no usable stashes!' Much sad :( Skipping current block....
    defaultdict(<type 'list'>, {'pruned': [], 'deadended': [], 'active': [], 'unconstrained': [], 'errored': [], 'unsat': [], 'stashed': []})
    [23:23:02,674] [WARNING] Symbolic Execution at block 0x45d9b0 failed: 'There are no usable stashes!' Much sad :( Skipping current block....
    [23:23:02,674] [+] 100% completed
    defaultdict(<type 'list'>, {'pruned': [], 'deadended': [], 'active': [], 'unconstrained': [], 'errored': [], 'unsat': [], 'stashed': []})
    [23:23:02,688] [WARNING] Symbolic Execution at block 0x45d9b4 failed: 'There are no usable stashes!' Much sad :( Skipping current block....
    [23:23:02,689] [+] Done.
    [23:23:02,689] [+] Saving basic block abstractions to a file...
    Traceback (most recent call last):
      File "./source/BOPC.py", line 501, in <module>
        abstract(mark, args.abstractions, args.binary)
      File "./source/BOPC.py", line 341, in abstract
        mark.save_abstractions(filename)
      File "/home/tullsen/src/3rd/BOPC/source/mark.py", line 423, in save_abstractions
        pickle.dump(abstr, output, 0)           # pickle dictionary using protocol 0.
      File "/usr/lib/python2.7/pickle.py", line 1376, in dump
        Pickler(file, protocol).dump(obj)
      File "/usr/lib/python2.7/pickle.py", line 224, in dump
        self.save(obj)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
        save(v)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
        save(v)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/usr/lib/python2.7/pickle.py", line 668, in _batch_setitems
        save(k)
      File "/usr/lib/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
      File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
        save(args)
      File "/usr/lib/python2.7/pickle.py", line 271, in save
        pid = self.persistent_id(obj)
      File "/usr/lib/python2.7/pickle.py", line 333, in persistent_id
        def persistent_id(self, obj):
      File "/home/tullsen/src/3rd/BOPC/source/absblk.py", line 851, in __sig_handler
        raise Exception("Alarm triggered after %d seconds" % ABSBLK_TIMEOUT)
    Exception: Alarm triggered after 5 seconds

From a quick look at the code, it seems like the exception defined on these lines:

    source/absblk.py:851:
    source/absblk.py:852:
    source/absblk.py:853:
    source/absblk.py:854:

cannot be raised once we get to source/mark.py:421.  But I must be mistaken because the following 'hack' does stop this from occurring:

    diff --git a/source/mark.py b/source/mark.py
    index 950150f..52f77f1 100755
    --- a/source/mark.py
    +++ b/source/mark.py
    @@ -58,6 +58,7 @@ import pprint
     import math
     import re

    +import signal

     # -------------------------------------------------------------------------------------------------
    @@ -418,6 +419,8 @@ class mark( object ):
             for node, _ in nx.get_node_attributes(self.__cfg.graph,'fail').iteritems():
                 fail.add(node.addr)

    +        signal.alarm(0)
             try:
                 output = open(filename + '.abs', 'wb')  # create the file
                 pickle.dump(abstr, output, 0)           # pickle dictionary using
             protocol 0.

**Comment by ispoleet** [comment]
As I said, you have to use the suggested networkx version. Interfaces are different and is expected to
get crashes here. Also this does not produces any solution. It's just for intermediate results. I'll release
proper instructions on how to run it on early December.

**Comment by balbassam** [comment]
Mark,

I think I found out your issue. Looking at your first crash log it appears that BOPc's internal alarm triggered which killed itself. I tested with a very slow computer and found that I was able to reproduce the issue.

It appears as though the internal timeout has been triggered. Please try to increase the `ABSBLK_TIMEOUT` variable up from 5 seconds and let me know if it works :)

**Comment by gannimo** [comment]
This could also be an unrelated error. `ABSBLK_TIMEOUT = 5` in its default configuration and it looks as if the timeout was triggered. Instead of running th example with `nginx`, try `sudo` which is a much smaller binary. If you want to run it on nginx, you may want to try increasing `ABSBLK_TIMEOUT` to, e.g., 60 instead of 5 in `config.py`

**Comment by mtullsen** [comment]
nginx1 finished (a little slower this time) with ABSBLK_TIMEOUT=60.  Thanks.
